<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Amazon SES (v2 API) provider for Core.Email</Description>
    <PackageTags>$(PackageTags) SES AWS Amazon</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SimpleEmailV2" />
    <PackageReference Include="MimeKit" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Email.Abstractions\Core.Email.Abstractions.csproj" />
  </ItemGroup>

</Project>