name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:

    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.ref_name }}

    steps:
    - uses: actions/checkout@v7

    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.x

    - name: Test
      run: dotnet test --configuration Release --filter "Category!=Integration"

    - name: Pack
      run: dotnet pack --configuration Release -p:Version="$VERSION" -p:GeneratePackageOnBuild=false --output artifacts

    - name: Publish
      run: dotnet nuget push "artifacts/*.nupkg" --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --skip-duplicate
